[package]
name = "keepass"
description = "KeePass .kdbx database file parser"
edition = "2018"

homepage = "https://github.com/sseemayer/keepass-rs"
repository = "https://github.com/sseemayer/keepass-rs"
documentation = "https://docs.rs/keepass"

version = "0.4.10"
authors = ["Stefan Seemayer <stefan@seemayer.de>"]
license = "MIT"

readme = "README.md"

[features]
utilities = ["clap", "rpassword"]

default = []

[dependencies]
byteorder = "1"
flate2 = "1"
secstr = "0.5"
xml-rs = "0.8"
base64 = "0.13"
hex-literal = "0.3"
rust-argon2 = "1.0.0"
sha2 = "0.10.2"
aes = "0.7.5"
block-modes = "0.8.1"
hmac = "0.12.1"
salsa20 = "0.10.2"
chacha20 = "0.9.0"
cipher = "0.4.3"
twofish = "0.7.1"
cbc = "0.1.2"
chrono = "0.4"

# dependencies for command-line utilities
clap = { version = "3.1.8", optional = true }
rpassword = { version = "6.0.1", optional = true }

[[bin]]
name = "kp-dump-xml"
required-features = ["utilities"]

[[bin]]
name = "kp-show-db"
required-features = ["utilities"]
