[package]
name = "keepass"
description = "KeePass .kdbx database file parser"

homepage = "https://github.com/sseemayer/keepass-rs"
repository = "https://github.com/sseemayer/keepass-rs"
documentation = "https://sseemayer.github.io/keepass-rs/"

version = "0.4.1"
authors = ["Stefan Seemayer <stefan@seemayer.de>"]
license = "MIT"

readme = "README.md"

[dependencies]
byteorder = "^1"
flate2 = "^0.2"
secstr = "^0.3"
xml-rs = "^0.6"
base64 = "^0.6"
hex-literal = "0.2.0"
rust-argon2 = "0.4.0"
sha2 = "0.8.0"
aes = "0.3.2"
block-modes = "0.3.3"
hmac = "0.7.0"
rust-crypto = "0.2.36"
